name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      POSTGRESQL_NAME: ${{ secrets.POSTGRESQL_NAME }}
      POSTGRESQL_USER: ${{ secrets.POSTGRESQL_USER }}
      POSTGRESQL_PWD: ${{ secrets.POSTGRESQL_PWD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Java 환경 세팅 (Amazon temurin JDK 21 사용)
      - name: Set up JDK 21 (Eclipse Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend (Spring Boot)
        run: |
          cd server  # server 디렉토리로 이동
          ./gradlew clean build  # Gradle 빌드 수행

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}    # EC2 서버 IP
          username: ${{ secrets.EC2_USER }}  # EC2 사용자명
          key: ${{ secrets.EC2_KEY }}      # SSH 개인 키
          port: 22
          script: |
            cd /home/ec2-user/app
            pkill -f 'java -jar' || echo "No app running"
            rm -rf *.jar

      - name: Deploy to EC2 using rsync
        run: |
          rsync -avz -e "ssh -i ${{ secrets.EC2_KEY }}" ./server/build/libs/*.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
      
      - name: Start Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/app
            nohup java -jar /home/ec2-user/app/*.jar --server.port=8080 > app.log 2>&1 &

